<h2>seznam uživatelů</h2>
<?php foreach ($this->users as $key => $value) { ?> 
        <tbody> 
            <tr>                            
                <td><?php print $value ['Name']; ?></td> 
                <td><?php print $value ['Surname']; ?></td> 
                <td><?php print $value ['Age']; ?></td> 
                <td><?php print $value ['Date']; ?></td> 
                <td class="edit-btn"><a href="<?php echo $this->url(array('controller' => 'User', 'action' => 'edit', 'id' => $value ['id'])); ?>"><i class="fa fa-pencil"></i></a></td>
                <td class="delete-btn"><a href="<?php echo $this->url(array('controller' => 'User', 'action' => 'delete', 'id' => $value ['id'])); ?>"><i class="fa fa-trash"></i></a></td>
            </tr>    
         <?php } ?>