<h2>seznam plánů cest</h2>
//<?php foreach ($this->plans as $key => $value) { ?> 
<!--        <tbody> 
            <tr>                            
                <td>//<?php print $value ['Area']; ?></td> 
                <td>//<?php print $value ['Arrive']; ?></td> 
                <td>//<?php print $value ['Departure']; ?></td> 
                <td>//<?php print $value ['Description']; ?></td>

               <td class="edit-btn"><a href="//<?php echo $this->url(array('controller' => 'TravelPlan', 'action' => 'edit-plans', 'Id' => $value ['TravelplanId'])); ?>"><i class="edit"></i>Edit</a></td> 
        <br>
              
              </tr>    -->
         //<?php } ?>