<h2>seznam plánů cest</h2>

<?php foreach ($this->plans as $key => $value) { ?> 
<table>    
    <tbody> 
            <tr>    
                <td><?php print $value ['Name']; ?></td>
                </tr>
            <tr>
                <td><?php print $value ['Area']; ?></td> 
                </tr>
             <tr>                         
                <td><?php print $value ['Arrive']; ?></td> 
                </tr>
             <tr>   
                <td><?php print $value ['Departure']; ?></td> 
                </tr>
             <tr>   
                <td><?php print $value ['Description']; ?></td>
                </tr>

               <td class="edit-btn"><a href="<?php echo $this->url(array('controller' => 'Travelplan', 'action' => 'edit-plans', 'Id' => $value ['TravelplanId'])); ?>"><i class="edit"></i>Edit</a></td> 
               <td class="delete-btn"><a href="<?php echo $this->url(array('controller' => 'Travelplan', 'action' => 'delete-plans', 'Id' => $value ['TravelplanId'])); ?>"><i class="fa fa-trash"></i>delete</a></td>
              
               <br>
        </tbody>
</table>
                  
         <?php } ?>