
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="PSPad editor, www.pspad.com">
  <title></title>
  </head>

<header>
    <nav>
        <ul>
            <li>
                <a>odkaz</a>
                <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'fetch-all-users')) ?>">uzivatele</a>
            </li>

        </ul>
    </nav>
</header>
<?php echo $this->layout()->content;

?>



<footer>paticka</footer>
