
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
 echo $this->doctype();
?> 
    <?php if (isset($this->message)) : ?>
        <div class="notification">
            <h5><span><i class="fa fa-info-circle fa-lg" aria-hidden="true"></i><b> </b><?php echo $this->message; ?></span></h5>
        </div>    
    <?php endif; ?>
<head>
    <script src="https://unpkg.com/react@latest/dist/react.js"></script>
    <script src="https://unpkg.com/react-dom@latest/dist/react-dom.js"></script>
    <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
    <?php
    echo $this->headMeta();
    echo $this->headTitle();
    
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('NOSPAM');
   
    echo $this->headLink()
            ->appendStylesheet($this->baseUrl() . '/css/main.css');

    
//    echo $this->HeadScript()
//            ->appendFile('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'text/javascript')
//            ->appendFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js', 'text/javascript');
//    ?> 
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--</head>
  <head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="PSPad editor, www.pspad.com">
  <title></title>
  </head>-->

<header>
    <nav>
        <?php print $this->navigation()->menu();?>
    </nav>
    <?php print $this->navigation()->breadcrumbs(); ?>
</header>
<?php echo $this->layout()->content;

?>



<footer>paticka</footer>
