
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
 echo $this->doctype();
?> 
    <?php if (isset($this->message)) : ?>
        <div class="notification">
            <h5><span><i class="fa fa-info-circle fa-lg" aria-hidden="true"></i><b> </b><?php echo $this->message; ?></span></h5>
        </div>    
    <?php endif; ?>
<head>
    <!-- REACT JS -->
    <script src="https://unpkg.com/react@latest/dist/react.js"></script>
    <script src="https://unpkg.com/react-dom@latest/dist/react-dom.js"></script>
    <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
    <!-- KONEC REACT JS -->
    
    <!-- winget kalendáře -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
    <script>
        

   $( function() {
    $(" #Departure,#Arrive").datepicker({
      format: 'yyyy-mm-dd'
     
    });
     } );
    </script>
    <!-- konec widgetu kalendáře-->
    <?php
    echo $this->headMeta();
    echo $this->headTitle();
    
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('NOSPAM');
   
    echo $this->headLink()
            ->appendStylesheet($this->baseUrl() . '/css/main.css');

    
//    echo $this->HeadScript()
//            ->appendFile('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'text/javascript')
//            ->appendFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js', 'text/javascript');
//    ?> 
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--</head>
  <head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="PSPad editor, www.pspad.com">
  <title></title>
  </head>-->

<header>
    <nav>
        <?php print $this->navigation()->menu()->setMinDepth(0)->setMaxDepth(0);?>
    </nav>
    <?php print $this->navigation()->breadcrumbs(); ?>
</header>
<div id="submenu">
    <?php
                    //echo $this->navigation()->menu()->setUlClass('nav navbar-nav')->setMinDepth(1)->setMaxDepth(1); 
                    echo $this->navigation()->menu()->renderMenu(null, array("minDepth" => 1, "maxDepth" => 2, "onlyActiveBranch" => true, "renderParents" => false, 'ulClass' => 'nav navbar-nav horizontal-menu'))
                    ?>
</div>

<?php echo $this->layout()->content;

?>




<footer>paticka</footer>
