<?php
$this->title = "Smazání";
$this->headTitle($this->title);
?>

<div class="message-info">
    <h3><i class="fa fa-trash-o"></i> Delete</h3><hr>
    <p>Do you really want to delete the domain <b>R<?php echo $this->escape($this->userDeleteForm['Surname']); ?>?</b></p> 
    <form action="<?php echo $this->url(array('action' => 'delete-users')); ?>" method="post">
        <div> 
            <input type="hidden" name="id" value="<?php echo $this->user['id']; ?>" /> 
            <input class="btn btn-danger" type="submit" name="del" value="Ano" /> 
            <input  class="btn btn-info" type="submit" name="del" value="Ne" />
        </div>
    </form>
</div>