
<h2>seznam uživatelů</h2>
<?php foreach ($this->users as $key => $value) { ?> 
        <tbody> 
            <tr>                            
                <td><?php print $value ['Name']; ?></td> 
                <td><?php print $value ['Surname']; ?></td> 

               <td class="edit-btn"><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'edit-users', 'id' => $value ['UserId'])); ?>"><i class="edit"></i>Edit</a></td> 
                <td class="delete-btn"><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'delete-users', 'id' => $value ['UserId'])); ?>"><i class="fa fa-trash"></i>delete</a></td><br>
              
              </tr>    
         <?php } ?>

<br /><br />
<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>fetchAllUsers</b></p>
</div>

