<h2>seznam zemí</h2>
//<?php foreach ($this->country as $key => $value) { ?> 
        <tbody> 
            <tr>                            
                <td>//<?php print $value ['CountryName']; ?></td> 
                <td>//<?php print $value ['Continent']; ?></td> 

<!--               <td class="edit-btn"><a href="//<?php echo $this->url(array('controller' => 'Country', 'action' => 'edit-country', 'Id' => $value ['CountryId'])); ?>"><i class="edit"></i>Edit</a></td> 
        <br>
              
              </tr>    -->
         //<?php } ?>