<h2>seznam uživatelů</h2>
<?php foreach ($this->users as $key => $value) { ?> 
        <tbody> 
            <tr>                            
                <td><?php print $value ['Name']; ?></td> 
                <td><?php print $value ['Surname']; ?></td> 

               <td class="edit-btn"><a href="<?php echo $this->url(array('controller' => 'User', 'action' => 'edit-users', 'Id' => $value ['UserId'])); ?>"><i class="edit"></i>Edit</a></td> 
<!--                <td class="delete-btn"><a href="<?php echo $this->url(array('controller' => 'User', 'action' => 'delete', 'Id' => $value ['id'])); ?>"><i class="fa fa-trash"></i></a></td>--><br>
              
              </tr>    
         <?php } ?>